version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      api-go-tools:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      frontend-production:
        dependency-type: production
        patterns:
          - "react"
          - "react-dom"
      frontend-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /api/typescript-generator
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      api-typescript-tools:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      container-images:
        patterns:
          - "*"
