// Package apimodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apimodels

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ApiErrorCode.
const (
	ApiErrorCodeForbidden              ApiErrorCode = "forbidden"
	ApiErrorCodeInvalidRequest         ApiErrorCode = "invalid_request"
	ApiErrorCodeMethodNotAllowed       ApiErrorCode = "method_not_allowed"
	ApiErrorCodeNotFound               ApiErrorCode = "not_found"
	ApiErrorCodeNotReady               ApiErrorCode = "not_ready"
	ApiErrorCodeOperationFailed        ApiErrorCode = "operation_failed"
	ApiErrorCodeTemporarilyUnavailable ApiErrorCode = "temporarily_unavailable"
	ApiErrorCodeUnauthorized           ApiErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ApiErrorCode enum.
func (e ApiErrorCode) Valid() bool {
	switch e {
	case ApiErrorCodeForbidden:
		return true
	case ApiErrorCodeInvalidRequest:
		return true
	case ApiErrorCodeMethodNotAllowed:
		return true
	case ApiErrorCodeNotFound:
		return true
	case ApiErrorCodeNotReady:
		return true
	case ApiErrorCodeOperationFailed:
		return true
	case ApiErrorCodeTemporarilyUnavailable:
		return true
	case ApiErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for AttestationErrorCode.
const (
	AttestationBusy        AttestationErrorCode = "attestation_busy"
	AttestationUnavailable AttestationErrorCode = "attestation_unavailable"
	FeatureUnavailable     AttestationErrorCode = "feature_unavailable"
)

// Valid indicates whether the value is a known member of the AttestationErrorCode enum.
func (e AttestationErrorCode) Valid() bool {
	switch e {
	case AttestationBusy:
		return true
	case AttestationUnavailable:
		return true
	case FeatureUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for AttestationJWKSKeysAlg.
const (
	AttestationJWKSKeysAlgEd25519 AttestationJWKSKeysAlg = "Ed25519"
)

// Valid indicates whether the value is a known member of the AttestationJWKSKeysAlg enum.
func (e AttestationJWKSKeysAlg) Valid() bool {
	switch e {
	case AttestationJWKSKeysAlgEd25519:
		return true
	default:
		return false
	}
}

// Defines values for AttestationJWKSKeysCrv.
const (
	AttestationJWKSKeysCrvEd25519 AttestationJWKSKeysCrv = "Ed25519"
)

// Valid indicates whether the value is a known member of the AttestationJWKSKeysCrv enum.
func (e AttestationJWKSKeysCrv) Valid() bool {
	switch e {
	case AttestationJWKSKeysCrvEd25519:
		return true
	default:
		return false
	}
}

// Defines values for AttestationJWKSKeysKty.
const (
	OKP AttestationJWKSKeysKty = "OKP"
)

// Valid indicates whether the value is a known member of the AttestationJWKSKeysKty enum.
func (e AttestationJWKSKeysKty) Valid() bool {
	switch e {
	case OKP:
		return true
	default:
		return false
	}
}

// Defines values for AttestationJWKSKeysUse.
const (
	Sig AttestationJWKSKeysUse = "sig"
)

// Valid indicates whether the value is a known member of the AttestationJWKSKeysUse enum.
func (e AttestationJWKSKeysUse) Valid() bool {
	switch e {
	case Sig:
		return true
	default:
		return false
	}
}

// Defines values for AttestationProtectedHeaderAlg.
const (
	AttestationProtectedHeaderAlgEd25519 AttestationProtectedHeaderAlg = "Ed25519"
)

// Valid indicates whether the value is a known member of the AttestationProtectedHeaderAlg enum.
func (e AttestationProtectedHeaderAlg) Valid() bool {
	switch e {
	case AttestationProtectedHeaderAlgEd25519:
		return true
	default:
		return false
	}
}

// Defines values for AttestationProtectedHeaderTyp.
const (
	ApplicationvaultsmithRotationAttestationJson AttestationProtectedHeaderTyp = "application/vaultsmith-rotation-attestation+json"
)

// Valid indicates whether the value is a known member of the AttestationProtectedHeaderTyp enum.
func (e AttestationProtectedHeaderTyp) Valid() bool {
	switch e {
	case ApplicationvaultsmithRotationAttestationJson:
		return true
	default:
		return false
	}
}

// Defines values for AttestationVerificationReason.
const (
	BindingMismatch      AttestationVerificationReason = "binding_mismatch"
	InputDigestMismatch  AttestationVerificationReason = "input_digest_mismatch"
	IssuerMismatch       AttestationVerificationReason = "issuer_mismatch"
	KeyRevoked           AttestationVerificationReason = "key_revoked"
	OutputDigestMismatch AttestationVerificationReason = "output_digest_mismatch"
	SignatureInvalid     AttestationVerificationReason = "signature_invalid"
	UnknownKey           AttestationVerificationReason = "unknown_key"
	UnsupportedVersion   AttestationVerificationReason = "unsupported_version"
)

// Valid indicates whether the value is a known member of the AttestationVerificationReason enum.
func (e AttestationVerificationReason) Valid() bool {
	switch e {
	case BindingMismatch:
		return true
	case InputDigestMismatch:
		return true
	case IssuerMismatch:
		return true
	case KeyRevoked:
		return true
	case OutputDigestMismatch:
		return true
	case SignatureInvalid:
		return true
	case UnknownKey:
		return true
	case UnsupportedVersion:
		return true
	default:
		return false
	}
}

// Defines values for DigestBindingAlgorithm.
const (
	Sha256 DigestBindingAlgorithm = "sha-256"
)

// Valid indicates whether the value is a known member of the DigestBindingAlgorithm enum.
func (e DigestBindingAlgorithm) Valid() bool {
	switch e {
	case Sha256:
		return true
	default:
		return false
	}
}

// Defines values for LegacyDecryptRequestMode.
const (
	Decrypt LegacyDecryptRequestMode = "decrypt"
)

// Valid indicates whether the value is a known member of the LegacyDecryptRequestMode enum.
func (e LegacyDecryptRequestMode) Valid() bool {
	switch e {
	case Decrypt:
		return true
	default:
		return false
	}
}

// Defines values for LegacyEncryptRequestMode.
const (
	Encrypt LegacyEncryptRequestMode = "encrypt"
)

// Valid indicates whether the value is a known member of the LegacyEncryptRequestMode enum.
func (e LegacyEncryptRequestMode) Valid() bool {
	switch e {
	case Encrypt:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRotateRequestMode.
const (
	LegacyRotateRequestModeRotate LegacyRotateRequestMode = "rotate"
)

// Valid indicates whether the value is a known member of the LegacyRotateRequestMode enum.
func (e LegacyRotateRequestMode) Valid() bool {
	switch e {
	case LegacyRotateRequestModeRotate:
		return true
	default:
		return false
	}
}

// Defines values for RotationAttestationClaimsOperation.
const (
	RotationAttestationClaimsOperationRotate RotationAttestationClaimsOperation = "rotate"
)

// Valid indicates whether the value is a known member of the RotationAttestationClaimsOperation enum.
func (e RotationAttestationClaimsOperation) Valid() bool {
	switch e {
	case RotationAttestationClaimsOperationRotate:
		return true
	default:
		return false
	}
}

// ApiError Safe stable code and human text. Clients ignore unknown properties.
type ApiError struct {
	// Code Stable machine-readable error code.
	Code ApiErrorCode `json:"code"`

	// Message Safe human text with no submitted values or underlying failure details.
	Message string `json:"message"`
}

// ApiErrorCode Stable machine-readable error code.
type ApiErrorCode string

// AttestationError defines model for AttestationError.
type AttestationError struct {
	Code    AttestationErrorCode `json:"code"`
	Message string               `json:"message"`
}

// AttestationErrorCode defines model for AttestationError.Code.
type AttestationErrorCode string

// AttestationErrorResponse defines model for AttestationErrorResponse.
type AttestationErrorResponse struct {
	Error AttestationError `json:"error"`
}

// AttestationJWKS defines model for AttestationJWKS.
type AttestationJWKS struct {
	Keys []struct {
		Alg AttestationJWKSKeysAlg `json:"alg"`
		Crv AttestationJWKSKeysCrv `json:"crv"`
		Kid string                 `json:"kid"`
		Kty AttestationJWKSKeysKty `json:"kty"`
		Use AttestationJWKSKeysUse `json:"use"`
		X   string                 `json:"x"`
	} `json:"keys"`
}

// AttestationJWKSKeysAlg defines model for AttestationJWKS.Keys.Alg.
type AttestationJWKSKeysAlg string

// AttestationJWKSKeysCrv defines model for AttestationJWKS.Keys.Crv.
type AttestationJWKSKeysCrv string

// AttestationJWKSKeysKty defines model for AttestationJWKS.Keys.Kty.
type AttestationJWKSKeysKty string

// AttestationJWKSKeysUse defines model for AttestationJWKS.Keys.Use.
type AttestationJWKSKeysUse string

// AttestationMetadata defines model for AttestationMetadata.
type AttestationMetadata struct {
	ActiveKid           string   `json:"activeKid"`
	AttestationVersions []int    `json:"attestationVersions"`
	Issuer              string   `json:"issuer"`
	JwksUri             string   `json:"jwksUri"`
	RevokedKids         []string `json:"revokedKids"`
}

// AttestationProtectedHeader defines model for AttestationProtectedHeader.
type AttestationProtectedHeader struct {
	Alg AttestationProtectedHeaderAlg `json:"alg"`
	Kid string                        `json:"kid"`
	Typ AttestationProtectedHeaderTyp `json:"typ"`
}

// AttestationProtectedHeaderAlg defines model for AttestationProtectedHeader.Alg.
type AttestationProtectedHeaderAlg string

// AttestationProtectedHeaderTyp defines model for AttestationProtectedHeader.Typ.
type AttestationProtectedHeaderTyp string

// AttestationVerificationReason defines model for AttestationVerificationReason.
type AttestationVerificationReason string

// DecryptRequest defines model for DecryptRequest.
type DecryptRequest struct {
	// VaultText UTF-8 Ansible Vault 1.1 or 1.2 text limited to 5 MiB by encoded bytes.
	VaultText string `json:"vaultText"`
}

// DecryptResponse Secret-bearing response. Clients ignore unknown properties.
type DecryptResponse struct {
	// Plaintext Valid UTF-8 plaintext limited to 1 MiB by encoded bytes.
	Plaintext string `json:"plaintext"`
}

// DigestBinding defines model for DigestBinding.
type DigestBinding struct {
	Algorithm DigestBindingAlgorithm `json:"algorithm"`
	Digest    string                 `json:"digest"`
}

// DigestBindingAlgorithm defines model for DigestBinding.Algorithm.
type DigestBindingAlgorithm string

// EncryptRequest defines model for EncryptRequest.
type EncryptRequest struct {
	// Plaintext UTF-8 plaintext limited to 1 MiB by encoded bytes. Empty is valid.
	Plaintext string `json:"plaintext"`
}

// EncryptResponse Secret-bearing response. Clients ignore unknown properties.
type EncryptResponse struct {
	// VaultText Ansible Vault 1.2/AES256 text labeled with the selected profile.
	VaultText string `json:"vaultText"`
}

// ErrorResponse Safe API error envelope. Clients ignore unknown properties.
type ErrorResponse struct {
	// Error Safe stable code and human text. Clients ignore unknown properties.
	Error ApiError `json:"error"`
}

// LegacyDecryptRequest defines model for LegacyDecryptRequest.
type LegacyDecryptRequest struct {
	Mode LegacyDecryptRequestMode `json:"mode"`

	// ProfileId Examples: production
	ProfileId ProfileId `json:"profileId"`

	// Value UTF-8 Ansible Vault text limited to 5 MiB by encoded bytes.
	Value string `json:"value"`
}

// LegacyDecryptRequestMode defines model for LegacyDecryptRequest.Mode.
type LegacyDecryptRequestMode string

// LegacyEncryptRequest defines model for LegacyEncryptRequest.
type LegacyEncryptRequest struct {
	Mode LegacyEncryptRequestMode `json:"mode"`

	// ProfileId Examples: production
	ProfileId ProfileId `json:"profileId"`

	// Value UTF-8 plaintext limited to 1 MiB by encoded bytes. Empty is valid.
	Value string `json:"value"`
}

// LegacyEncryptRequestMode defines model for LegacyEncryptRequest.Mode.
type LegacyEncryptRequestMode string

// LegacyOperationRequest defines model for LegacyOperationRequest.
type LegacyOperationRequest struct {
	union json.RawMessage
}

// LegacyRotateRequest defines model for LegacyRotateRequest.
type LegacyRotateRequest struct {
	// DestinationProfileId Examples: production
	DestinationProfileId ProfileId               `json:"destinationProfileId"`
	Mode                 LegacyRotateRequestMode `json:"mode"`

	// SourceProfileId Examples: production
	SourceProfileId ProfileId `json:"sourceProfileId"`

	// Value UTF-8 Ansible Vault text limited to 5 MiB by encoded bytes.
	Value string `json:"value"`
}

// LegacyRotateRequestMode defines model for LegacyRotateRequest.Mode.
type LegacyRotateRequestMode string

// LegacyValueResponse Deprecated generic success response. Clients ignore unknown properties.
type LegacyValueResponse struct {
	Value string `json:"value"`
}

// Profile Safe public profile metadata. Clients ignore unknown properties.
type Profile struct {
	// Capabilities Effective caller capabilities. Clients ignore unknown properties.
	Capabilities ProfileCapabilities `json:"capabilities"`

	// Id Examples: production
	Id    ProfileId `json:"id"`
	Label string    `json:"label"`
}

// ProfileCapabilities Effective caller capabilities. Clients ignore unknown properties.
type ProfileCapabilities struct {
	Decrypt           bool `json:"decrypt"`
	Encrypt           bool `json:"encrypt"`
	RotateDestination bool `json:"rotateDestination"`
	RotateSource      bool `json:"rotateSource"`
}

// ProfileId Examples: production
type ProfileId = string

// ProfilesResponse Ordered visible profile catalog. Clients ignore unknown properties.
type ProfilesResponse struct {
	Profiles []Profile `json:"profiles"`
}

// RotateRequest defines model for RotateRequest.
type RotateRequest struct {
	// Attestation Optional request to bind the rotation result to caller context.
	Attestation *RotationAttestationRequest `json:"attestation,omitempty"`

	// DestinationProfileId Examples: production
	DestinationProfileId ProfileId `json:"destinationProfileId"`

	// SourceProfileId Examples: production
	SourceProfileId ProfileId `json:"sourceProfileId"`

	// VaultText UTF-8 Ansible Vault 1.1 or 1.2 text limited to 5 MiB by encoded bytes.
	VaultText string `json:"vaultText"`
}

// RotateResponse Secret-bearing response. Clients ignore unknown properties.
type RotateResponse struct {
	Attestation *RotationAttestation `json:"attestation,omitempty"`

	// VaultText Ansible Vault 1.2/AES256 text labeled with the destination profile.
	VaultText string `json:"vaultText"`
}

// RotationAttestation defines model for RotationAttestation.
type RotationAttestation struct {
	// Payload Unpadded base64url canonical JCS claims.
	Payload string `json:"payload"`

	// Protected Unpadded base64url protected JWS header.
	Protected string `json:"protected"`

	// Signature Unpadded base64url pure Ed25519 signature.
	Signature string `json:"signature"`
}

// RotationAttestationClaims defines model for RotationAttestationClaims.
type RotationAttestationClaims struct {
	// Binding Partial exact-match binding. At least one field is required.
	Binding *RotationBinding `json:"binding,omitempty"`

	// DestinationProfileId Examples: production
	DestinationProfileId ProfileId                          `json:"destinationProfileId"`
	IssuedAt             time.Time                          `json:"issuedAt"`
	Issuer               string                             `json:"issuer"`
	Kid                  string                             `json:"kid"`
	Operation            RotationAttestationClaimsOperation `json:"operation"`

	// SourceProfileId Examples: production
	SourceProfileId ProfileId `json:"sourceProfileId"`
}

// RotationAttestationClaimsOperation defines model for RotationAttestationClaims.Operation.
type RotationAttestationClaimsOperation string

// RotationAttestationRequest Optional request to bind the rotation result to caller context.
type RotationAttestationRequest struct {
	// Binding Partial exact-match binding. At least one field is required.
	Binding *RotationBinding `json:"binding,omitempty"`
}

// RotationBinding Partial exact-match binding. At least one field is required.
type RotationBinding struct {
	Path       *string `json:"path,omitempty"`
	Repository *string `json:"repository,omitempty"`
	Revision   *string `json:"revision,omitempty"`
	Selector   *string `json:"selector,omitempty"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	AttestationEnabled bool    `json:"attestationEnabled"`
	AuthRequired       bool    `json:"authRequired"`
	Authenticated      bool    `json:"authenticated"`
	CsrfToken          string  `json:"csrfToken"`
	Email              *string `json:"email,omitempty"`
}

// VerifyAttestationRequest defines model for VerifyAttestationRequest.
type VerifyAttestationRequest struct {
	Attestation RotationAttestation `json:"attestation"`

	// ExpectedBinding Partial exact-match binding. At least one field is required.
	ExpectedBinding *RotationBinding `json:"expectedBinding,omitempty"`
	InputVaultText  string           `json:"inputVaultText"`
	OutputVaultText string           `json:"outputVaultText"`
}

// VerifyAttestationResponse defines model for VerifyAttestationResponse.
type VerifyAttestationResponse struct {
	Attestation *RotationAttestationClaims     `json:"attestation,omitempty"`
	Reason      *AttestationVerificationReason `json:"reason,omitempty"`
	Valid       bool                           `json:"valid"`
}

// AttestationServiceUnavailable defines model for AttestationServiceUnavailable.
type AttestationServiceUnavailable = AttestationErrorResponse

// Forbidden Safe API error envelope. Clients ignore unknown properties.
type Forbidden = ErrorResponse

// InvalidRequest Safe API error envelope. Clients ignore unknown properties.
type InvalidRequest = ErrorResponse

// MethodNotAllowedGet Safe API error envelope. Clients ignore unknown properties.
type MethodNotAllowedGet = ErrorResponse

// MethodNotAllowedPost Safe API error envelope. Clients ignore unknown properties.
type MethodNotAllowedPost = ErrorResponse

// NotFound Safe API error envelope. Clients ignore unknown properties.
type NotFound = ErrorResponse

// OperationFailed Safe API error envelope. Clients ignore unknown properties.
type OperationFailed = ErrorResponse

// RequestTooLarge Safe API error envelope. Clients ignore unknown properties.
type RequestTooLarge = ErrorResponse

// ServiceUnavailable Safe API error envelope. Clients ignore unknown properties.
type ServiceUnavailable = ErrorResponse

// Unauthorized Safe API error envelope. Clients ignore unknown properties.
type Unauthorized = ErrorResponse

// UnauthorizedLegacy Safe API error envelope. Clients ignore unknown properties.
type UnauthorizedLegacy = ErrorResponse

// UnsupportedMediaType Safe API error envelope. Clients ignore unknown properties.
type UnsupportedMediaType = ErrorResponse

// VerifyAttestationJSONRequestBody defines body for VerifyAttestation for application/json ContentType.
type VerifyAttestationJSONRequestBody = VerifyAttestationRequest

// LegacyOperationJSONRequestBody defines body for LegacyOperation for application/json ContentType.
//
// Deprecated: this type has been marked as deprecated upstream, but no `x-deprecated-reason` was set
type LegacyOperationJSONRequestBody = LegacyOperationRequest

// DecryptValueJSONRequestBody defines body for DecryptValue for application/json ContentType.
type DecryptValueJSONRequestBody = DecryptRequest

// EncryptValueJSONRequestBody defines body for EncryptValue for application/json ContentType.
type EncryptValueJSONRequestBody = EncryptRequest

// RotateValueJSONRequestBody defines body for RotateValue for application/json ContentType.
type RotateValueJSONRequestBody = RotateRequest

// AsLegacyEncryptRequest returns the union data inside the LegacyOperationRequest as a LegacyEncryptRequest
func (t LegacyOperationRequest) AsLegacyEncryptRequest() (LegacyEncryptRequest, error) {
	var body LegacyEncryptRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyEncryptRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyEncryptRequest
func (t *LegacyOperationRequest) FromLegacyEncryptRequest(v LegacyEncryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"encrypt"}`))
	t.union = b
	return err
}

// MergeLegacyEncryptRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyEncryptRequest
func (t *LegacyOperationRequest) MergeLegacyEncryptRequest(v LegacyEncryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"encrypt"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLegacyDecryptRequest returns the union data inside the LegacyOperationRequest as a LegacyDecryptRequest
func (t LegacyOperationRequest) AsLegacyDecryptRequest() (LegacyDecryptRequest, error) {
	var body LegacyDecryptRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyDecryptRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyDecryptRequest
func (t *LegacyOperationRequest) FromLegacyDecryptRequest(v LegacyDecryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"decrypt"}`))
	t.union = b
	return err
}

// MergeLegacyDecryptRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyDecryptRequest
func (t *LegacyOperationRequest) MergeLegacyDecryptRequest(v LegacyDecryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"decrypt"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLegacyRotateRequest returns the union data inside the LegacyOperationRequest as a LegacyRotateRequest
func (t LegacyOperationRequest) AsLegacyRotateRequest() (LegacyRotateRequest, error) {
	var body LegacyRotateRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyRotateRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyRotateRequest
func (t *LegacyOperationRequest) FromLegacyRotateRequest(v LegacyRotateRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"rotate"}`))
	t.union = b
	return err
}

// MergeLegacyRotateRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyRotateRequest
func (t *LegacyOperationRequest) MergeLegacyRotateRequest(v LegacyRotateRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"rotate"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LegacyOperationRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t LegacyOperationRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "decrypt":
		return t.AsLegacyDecryptRequest()
	case "encrypt":
		return t.AsLegacyEncryptRequest()
	case "rotate":
		return t.AsLegacyRotateRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t LegacyOperationRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LegacyOperationRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
