// Package apimodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apimodels

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ApiErrorCode.
const (
	ApiErrorCodeForbidden              ApiErrorCode = "forbidden"
	ApiErrorCodeInvalidRequest         ApiErrorCode = "invalid_request"
	ApiErrorCodeMethodNotAllowed       ApiErrorCode = "method_not_allowed"
	ApiErrorCodeNotFound               ApiErrorCode = "not_found"
	ApiErrorCodeNotReady               ApiErrorCode = "not_ready"
	ApiErrorCodeOperationFailed        ApiErrorCode = "operation_failed"
	ApiErrorCodeTemporarilyUnavailable ApiErrorCode = "temporarily_unavailable"
	ApiErrorCodeUnauthorized           ApiErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ApiErrorCode enum.
func (e ApiErrorCode) Valid() bool {
	switch e {
	case ApiErrorCodeForbidden:
		return true
	case ApiErrorCodeInvalidRequest:
		return true
	case ApiErrorCodeMethodNotAllowed:
		return true
	case ApiErrorCodeNotFound:
		return true
	case ApiErrorCodeNotReady:
		return true
	case ApiErrorCodeOperationFailed:
		return true
	case ApiErrorCodeTemporarilyUnavailable:
		return true
	case ApiErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for LegacyDecryptRequestMode.
const (
	Decrypt LegacyDecryptRequestMode = "decrypt"
)

// Valid indicates whether the value is a known member of the LegacyDecryptRequestMode enum.
func (e LegacyDecryptRequestMode) Valid() bool {
	switch e {
	case Decrypt:
		return true
	default:
		return false
	}
}

// Defines values for LegacyEncryptRequestMode.
const (
	Encrypt LegacyEncryptRequestMode = "encrypt"
)

// Valid indicates whether the value is a known member of the LegacyEncryptRequestMode enum.
func (e LegacyEncryptRequestMode) Valid() bool {
	switch e {
	case Encrypt:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRotateRequestMode.
const (
	Rotate LegacyRotateRequestMode = "rotate"
)

// Valid indicates whether the value is a known member of the LegacyRotateRequestMode enum.
func (e LegacyRotateRequestMode) Valid() bool {
	switch e {
	case Rotate:
		return true
	default:
		return false
	}
}

// ApiError Safe stable code and human text. Clients ignore unknown properties.
type ApiError struct {
	// Code Stable machine-readable error code.
	Code ApiErrorCode `json:"code"`

	// Message Safe human text with no submitted values or underlying failure details.
	Message string `json:"message"`
}

// ApiErrorCode Stable machine-readable error code.
type ApiErrorCode string

// DecryptRequest defines model for DecryptRequest.
type DecryptRequest struct {
	// VaultText UTF-8 Ansible Vault 1.1 or 1.2 text limited to 5 MiB by encoded bytes.
	VaultText string `json:"vaultText"`
}

// DecryptResponse Secret-bearing response. Clients ignore unknown properties.
type DecryptResponse struct {
	// Plaintext Valid UTF-8 plaintext limited to 1 MiB by encoded bytes.
	Plaintext string `json:"plaintext"`
}

// EncryptRequest defines model for EncryptRequest.
type EncryptRequest struct {
	// Plaintext UTF-8 plaintext limited to 1 MiB by encoded bytes. Empty is valid.
	Plaintext string `json:"plaintext"`
}

// EncryptResponse Secret-bearing response. Clients ignore unknown properties.
type EncryptResponse struct {
	// VaultText Ansible Vault 1.2/AES256 text labeled with the selected profile.
	VaultText string `json:"vaultText"`
}

// ErrorResponse Safe API error envelope. Clients ignore unknown properties.
type ErrorResponse struct {
	// Error Safe stable code and human text. Clients ignore unknown properties.
	Error ApiError `json:"error"`
}

// LegacyDecryptRequest defines model for LegacyDecryptRequest.
type LegacyDecryptRequest struct {
	Mode LegacyDecryptRequestMode `json:"mode"`

	// ProfileId Examples: production
	ProfileId ProfileId `json:"profileId"`

	// Value UTF-8 Ansible Vault text limited to 5 MiB by encoded bytes.
	Value string `json:"value"`
}

// LegacyDecryptRequestMode defines model for LegacyDecryptRequest.Mode.
type LegacyDecryptRequestMode string

// LegacyEncryptRequest defines model for LegacyEncryptRequest.
type LegacyEncryptRequest struct {
	Mode LegacyEncryptRequestMode `json:"mode"`

	// ProfileId Examples: production
	ProfileId ProfileId `json:"profileId"`

	// Value UTF-8 plaintext limited to 1 MiB by encoded bytes. Empty is valid.
	Value string `json:"value"`
}

// LegacyEncryptRequestMode defines model for LegacyEncryptRequest.Mode.
type LegacyEncryptRequestMode string

// LegacyOperationRequest defines model for LegacyOperationRequest.
type LegacyOperationRequest struct {
	union json.RawMessage
}

// LegacyRotateRequest defines model for LegacyRotateRequest.
type LegacyRotateRequest struct {
	// DestinationProfileId Examples: production
	DestinationProfileId ProfileId               `json:"destinationProfileId"`
	Mode                 LegacyRotateRequestMode `json:"mode"`

	// SourceProfileId Examples: production
	SourceProfileId ProfileId `json:"sourceProfileId"`

	// Value UTF-8 Ansible Vault text limited to 5 MiB by encoded bytes.
	Value string `json:"value"`
}

// LegacyRotateRequestMode defines model for LegacyRotateRequest.Mode.
type LegacyRotateRequestMode string

// LegacyValueResponse Deprecated generic success response. Clients ignore unknown properties.
type LegacyValueResponse struct {
	Value string `json:"value"`
}

// Profile Safe public profile metadata. Clients ignore unknown properties.
type Profile struct {
	// Capabilities Effective caller capabilities. Clients ignore unknown properties.
	Capabilities ProfileCapabilities `json:"capabilities"`

	// Id Examples: production
	Id    ProfileId `json:"id"`
	Label string    `json:"label"`
}

// ProfileCapabilities Effective caller capabilities. Clients ignore unknown properties.
type ProfileCapabilities struct {
	Decrypt           bool `json:"decrypt"`
	Encrypt           bool `json:"encrypt"`
	RotateDestination bool `json:"rotateDestination"`
	RotateSource      bool `json:"rotateSource"`
}

// ProfileId Examples: production
type ProfileId = string

// ProfilesResponse Ordered visible profile catalog. Clients ignore unknown properties.
type ProfilesResponse struct {
	Profiles []Profile `json:"profiles"`
}

// RotateRequest defines model for RotateRequest.
type RotateRequest struct {
	// DestinationProfileId Examples: production
	DestinationProfileId ProfileId `json:"destinationProfileId"`

	// SourceProfileId Examples: production
	SourceProfileId ProfileId `json:"sourceProfileId"`

	// VaultText UTF-8 Ansible Vault 1.1 or 1.2 text limited to 5 MiB by encoded bytes.
	VaultText string `json:"vaultText"`
}

// RotateResponse Secret-bearing response. Clients ignore unknown properties.
type RotateResponse struct {
	// VaultText Ansible Vault 1.2/AES256 text labeled with the destination profile.
	VaultText string `json:"vaultText"`
}

// Forbidden Safe API error envelope. Clients ignore unknown properties.
type Forbidden = ErrorResponse

// InvalidRequest Safe API error envelope. Clients ignore unknown properties.
type InvalidRequest = ErrorResponse

// MethodNotAllowedGet Safe API error envelope. Clients ignore unknown properties.
type MethodNotAllowedGet = ErrorResponse

// MethodNotAllowedPost Safe API error envelope. Clients ignore unknown properties.
type MethodNotAllowedPost = ErrorResponse

// NotFound Safe API error envelope. Clients ignore unknown properties.
type NotFound = ErrorResponse

// OperationFailed Safe API error envelope. Clients ignore unknown properties.
type OperationFailed = ErrorResponse

// RequestTooLarge Safe API error envelope. Clients ignore unknown properties.
type RequestTooLarge = ErrorResponse

// ServiceUnavailable Safe API error envelope. Clients ignore unknown properties.
type ServiceUnavailable = ErrorResponse

// Unauthorized Safe API error envelope. Clients ignore unknown properties.
type Unauthorized = ErrorResponse

// UnauthorizedLegacy Safe API error envelope. Clients ignore unknown properties.
type UnauthorizedLegacy = ErrorResponse

// UnsupportedMediaType Safe API error envelope. Clients ignore unknown properties.
type UnsupportedMediaType = ErrorResponse

// LegacyOperationJSONRequestBody defines body for LegacyOperation for application/json ContentType.
//
// Deprecated: this type has been marked as deprecated upstream, but no `x-deprecated-reason` was set
type LegacyOperationJSONRequestBody = LegacyOperationRequest

// DecryptValueJSONRequestBody defines body for DecryptValue for application/json ContentType.
type DecryptValueJSONRequestBody = DecryptRequest

// EncryptValueJSONRequestBody defines body for EncryptValue for application/json ContentType.
type EncryptValueJSONRequestBody = EncryptRequest

// RotateValueJSONRequestBody defines body for RotateValue for application/json ContentType.
type RotateValueJSONRequestBody = RotateRequest

// AsLegacyEncryptRequest returns the union data inside the LegacyOperationRequest as a LegacyEncryptRequest
func (t LegacyOperationRequest) AsLegacyEncryptRequest() (LegacyEncryptRequest, error) {
	var body LegacyEncryptRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyEncryptRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyEncryptRequest
func (t *LegacyOperationRequest) FromLegacyEncryptRequest(v LegacyEncryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"encrypt"}`))
	t.union = b
	return err
}

// MergeLegacyEncryptRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyEncryptRequest
func (t *LegacyOperationRequest) MergeLegacyEncryptRequest(v LegacyEncryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"encrypt"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLegacyDecryptRequest returns the union data inside the LegacyOperationRequest as a LegacyDecryptRequest
func (t LegacyOperationRequest) AsLegacyDecryptRequest() (LegacyDecryptRequest, error) {
	var body LegacyDecryptRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyDecryptRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyDecryptRequest
func (t *LegacyOperationRequest) FromLegacyDecryptRequest(v LegacyDecryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"decrypt"}`))
	t.union = b
	return err
}

// MergeLegacyDecryptRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyDecryptRequest
func (t *LegacyOperationRequest) MergeLegacyDecryptRequest(v LegacyDecryptRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"decrypt"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLegacyRotateRequest returns the union data inside the LegacyOperationRequest as a LegacyRotateRequest
func (t LegacyOperationRequest) AsLegacyRotateRequest() (LegacyRotateRequest, error) {
	var body LegacyRotateRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyRotateRequest overwrites any union data inside the LegacyOperationRequest as the provided LegacyRotateRequest
func (t *LegacyOperationRequest) FromLegacyRotateRequest(v LegacyRotateRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"rotate"}`))
	t.union = b
	return err
}

// MergeLegacyRotateRequest performs a merge with any union data inside the LegacyOperationRequest, using the provided LegacyRotateRequest
func (t *LegacyOperationRequest) MergeLegacyRotateRequest(v LegacyRotateRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"mode":"rotate"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LegacyOperationRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t LegacyOperationRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "decrypt":
		return t.AsLegacyDecryptRequest()
	case "encrypt":
		return t.AsLegacyEncryptRequest()
	case "rotate":
		return t.AsLegacyRotateRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t LegacyOperationRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LegacyOperationRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
