[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = vaultsmithHasRole(r.sub, p.sub) && vaultsmithMatch(r.obj, p.obj) && r.act == p.act
