{{- include "vaultsmith.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultsmith.fullname" . }}
  labels:
    {{- include "vaultsmith.labels" . | nindent 4 }}
data:
  profiles.json: |-
    [
    {{- range $index, $profile := .Values.profiles }}
      {{- if $index }},{{ end }}
      {"id": {{ toJson $profile.id }}, "label": {{ toJson $profile.label }}, "passwordEnv": {{ toJson $profile.passwordEnv }}}
    {{- end }}
    ]
  {{- if .Values.auth.policy.data }}
  {{ .Values.auth.policy.key | quote }}: |-
{{ .Values.auth.policy.data | nindent 4 }}
  {{- end }}
